### ISSUE TITLE
This API yet work?

### ISSUE THREAD

**Issue by MrProscrite** [marciovsena/abibliadigital#243]
I woul know if this api work yet, because i'm trying create an users but i cant do this.

**Comment by JamilFilho** [comment]
Yes, it's working perfectly.

You must make a POST request at the endpoint: `https://www.abibliadigital.com.br/api/users/`. Passing these parameters in the body:

```json
{
   "name": "Name",
   "email": "email@exemple.com",
   "password": "password",
   "notifications": true
}
```

Make sure that the password is at least 6 characters long.
