### ISSUE TITLE
I'm not able to use

### ISSUE THREAD

**Issue by MDSSCML** [marciovsena/abibliadigital#303]
Good afternoon, it's not a problem, I'm not able to use this api.
POST https://www.abibliadigital.com.br/api/verses/search.
maybe if you could put a practical example, thank you.

**Comment by marciovsena** [comment]
Thanks for the question. There is documentation [here](https://github.com/marciovsena/abibliadigital/blob/master/DOCUMENTATION.md) for reference with a practical example of using this endpoint.
