### ISSUE TITLE
can't update token

### ISSUE THREAD

**Issue by phamdat080598** [marciovsena/abibliadigital#342]
Hello Devs,

I am trying update token but the error is happen. Please help me to use this API.
Thank you.

API: https://www.abibliadigital.com.br/api/users/token
body response:
{
    "msg": "Oops! An unexpected error has occurred, create an [issue](https://github.com/marciovsena/abibliadigital/issues/new) with the information of this request.",
    "err": {}
}

**Comment by marciovsena** [comment]
@phamdat080598 problems fixed, please try again.
