### ISSUE TITLE
Is it possible to have it in any Spanish version? 

### ISSUE THREAD

**Issue by crismaver1993** [marciovsena/abibliadigital#363]
**Additional context**
I would like to have the possibility of do request for Spanish version. 

One question? 

In your description said: _RESTful Bible API with 7 versions, 4 languages and multiple features to simplify your day to day._

what are the others 3 languages?

**Comment by marciovsena** [comment]
We have no forecast for new languages. Time is short and we have had few contributions.

We currently have:

- 3 Portuguese Versions - (NVI, RA, ACF)
- 2 English Versions - (KJV, BBE)
- 1 Version in French - (APEE)
- 1 Castilian Version - (RVR)

Att.
