### ISSUE TITLE
Api não está funcionando.

### ISSUE THREAD

**Issue by MDSSCML** [marciovsena/abibliadigital#372]
**Describe the bug**
Nenhuma api está funcionando.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by marciovsena** [comment]
@MDSSCML Thank you very much. Problem fixed. If you have an interruption problem, please let me know on twitter: https://twitter.com/marciovsena
