### ISSUE TITLE
I had a error 

### ISSUE THREAD

**Issue by JonatanJSM** [marciovsena/abibliadigital#373]
Hello I had the following error
{
msg: "Oops! An unexpected error has occurred, create an [issue](https://github.com/marciovsena/abibliadigital/issues/new) with the information of this request.",
[err](https://www.abibliadigital.com.br/): {
command: "GET",
code: "NR_CLOSED",
[args](https://www.abibliadigital.com.br/): [
"187.147.67.127"
]
}
}
So I want to report this error because the message say create an [issue](https://github.com/marciovsena/abibliadigital/issues/new) with the information of this request
![error](https://user-images.githubusercontent.com/72703077/206765778-823d60c0-e328-4119-a1d0-583664f1d09f.png)

**Comment by marciovsena** [comment]
@JonatanJSM Thank you very much. Problem fixed. If you have an interruption problem, please let me know on twitter: https://twitter.com/marciovsena
