### ISSUE TITLE
Add Spanish NTV version

### ISSUE THREAD

**Issue by marvlm** [marciovsena/abibliadigital#40]
**As a** Spanish speaker developer
**I want to** be able to consult the spanish NTV version of the Bible
**So that** I can develop an app to share the Bible with people who speaks Spanish

**Comment by marciovsena** [comment]
We have no forecast for new languages. Time is short and we have had few contributions.

We currently have:

- 3 Portuguese Versions - (NVI, RA, ACF)
- 2 English Versions - (KJV, BBE)
- 1 Version in French - (APEE)
- 1 Castilian Version - (RVR)

Att.
