### ISSUE TITLE
Add Spanish NVI version

### ISSUE THREAD

**Issue by marvlm** [marciovsena/abibliadigital#41]
**As a** Spanish speaker developer
**I want to** be able to consult the spanish NVI version of the Bible
**So that** I can develop an app to share the Bible with people who speaks Spanish

**Comment by felipevegaaraujo** [comment]
Awesome, can we include the Reina Valera 1960 version in your request?

**Comment by crismaver1993** [comment]
@felipevegaaraujo  Do you have any Spanish version?

In your description said: _RESTful Bible API with 7 versions, 4 languages and multiple features to simplify your day to day._

But I dont know how to add language to the request

**Comment by htadashi** [comment]
@crismaver1993 
You need to add the bible version in the request. I think the only bible available in Spanish in the API is RVR (Reina-Valera), so the request would be:
https://www.abibliadigital.com.br/api/verses/rvr/sl/23

I think this architecture makes sense as a single language can have multiple versions of Bible.
